# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('idd', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(max_length=100)),
                ('gravatar_id', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('html_url', models.CharField(max_length=100)),
                ('followers_url', models.CharField(max_length=100)),
                ('following_url', models.CharField(max_length=100)),
                ('gists_url', models.CharField(max_length=100)),
                ('starred_url', models.CharField(max_length=100)),
                ('subscriptions_url', models.CharField(max_length=100)),
                ('organizations_url', models.CharField(max_length=100)),
                ('repos_url', models.CharField(max_length=100)),
                ('events_url', models.CharField(max_length=100)),
                ('received_events_url', models.CharField(max_length=100)),
                ('typ', models.CharField(max_length=100)),
                ('site_admin', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('hireable', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('public_repos', models.CharField(max_length=100)),
                ('public_gists', models.CharField(max_length=100)),
                ('followers', models.CharField(max_length=100)),
                ('following', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
                ('dat', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateField()),
            ],
        ),
    ]
