# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-27 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='company',
            field=models.CharField(default='company', max_length=100),
        ),
    ]
