# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-27 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180827_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='company',
            field=models.CharField(default='nll', max_length=100),
        ),
    ]
