# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180827_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='dat',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sapi',
            name='dat',
            field=models.DateField(null=True),
        ),
    ]
