# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180828_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='dat',
            field=models.DateField(default='l'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sapi',
            name='dat',
            field=models.DateField(default='l'),
            preserve_default=False,
        ),
    ]
